### ISSUE TITLE
Exception in sendPushConfiguration (pushConfig is null)

### ISSUE THREAD

**Issue by Amphiluke** [Donky-Network/cordova-plugin-donky-jsmodular#1]
Hello there,

We have an app which uses the `cordova-plugin-donky-jsmodular` plugin. When the app is launched _for the first time_ (i.e. `localStorage` is clean, and there is no any Donky-related data stored), the following exception is thrown:

> `[vjbz] : 2016-10-12T11:05:52.088Z [Error] : caught exception in sendPushConfiguration() : TypeError: null is not an object (evaluating 'pushConfig.registrationId')`

Here is a screenshot from the Safari inspector (debugging on device, iOS 10.0.2)
<img width="776" alt="donky-exception" src="https://cloud.githubusercontent.com/assets/1937729/19310092/98ddb0bc-90b2-11e6-8912-f5df51a0ad84.png">

This is reproduced in the official [Sample app](https://github.com/Donky-Network/Donky-Cordova-JSModular-Samples) as well.

I wonder if this somehow affects the work of Donky as everything else seems to go as expected (at least on the outside).  Anyway, it would be great to get rid of this error in Donky logs.

**Comment by Univibe69** [comment]
I have just reproduced this issue and can confirm that it doesn't affect the working of the SDK at all. You correctly identified that it only occurs the first time the app is launched - the plugin is handling an internal event and making an incorrect assumption about what data is stored.

I will fix the issue which will result in a new release of the plugin - in the meantime the existing release is 100%  functional apart from the error log entry.

**Comment by Amphiluke** [comment]
Okay, thanks for the quick reply. It's great to hear that the plugin functionality isn't affected by this issue.

**Comment by Univibe69** [comment]
Fixed in 1.0.5 release
